### PR TITLE
Move JSTS to peer dependency.

### LINKED ISSUE #60: Import JSTS from external package
Controls that use JSTS code should not import JSTS files by referencing the full path to the node_modules directory. Instead Webpack should import and compile JSTS files by referencing the JSTS package. Right now this will not work, because Webpack will not compile files from external packages. Maybe use and configure [babel-loader](https://github.com/babel/babel-loader).

### PR DESCRIPTION
**Pull request by friedjoff**
This will fix broken builds in Firefox, because Neutrino does not compile
external NPM packages correctly. In addition the bundle size is reduced
significantly and support for IE >= 10 has been added. Usage of topology
controls will require JSTS to be available globally (see index.html).

Fixes #60 and #62.

### CODE REVIEW

File: .neutrinorc.js [hunk 1]
```diff
@@ -7,12 +7,26 @@ const styleLoader = require('@neutrinojs/style-loader');
...
+          }
+        }]
+      ]
+    }
+  });
   neutrino.use(imageLoader);
   neutrino.use(styleLoader, { extract: false });
   neutrino.use(devServer);
 
+  // neutrino.config.plugins.delete('babel-minify').end();
```
Comment (lb1c) [inline .neutrinorc.js]: What's the reason for adding commented code?

Comment (friedjoff) [reply .neutrinorc.js]: Useful for debugging.
